[font.normal]
family = "FiraCode Nerd Font"
style = "regular"

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "zellij attach || zellij"]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[window.dimensions]
columns = 257
lines = 115

[window.position]
x = 1550
y = 0
