# Aliases to reach different repos
alias cdsi='cd $HOME/src/github.com/solo-io'
alias cdg='cd $HOME/src/github.com/solo-io/gloo'
alias nvg='nvim $HOME/src/github.com/solo-io/gloo/README.md'
alias cdgf='cd $HOME/src/github.com/solo-io/gloo-fed'
alias nvgf='nvim $HOME/src/github.com/solo-io/gloo-fed/README.md'
alias cdsp='cd $HOME/src/github.com/solo-io/solo-projects'
alias nvsp='nvim $HOME/src/github.com/solo-io/solo-projects/README.md'
alias cdsa='cd $HOME/src/github.com/solo-io/solo-apis'
alias nvsa='nvim $HOME/src/github.com/solo-io/solo-apis/README.md'
alias cddp='cd $HOME/src/github.com/solo-io/dev-portal'
alias nvdp='nvim $HOME/src/github.com/solo-io/dev-portal/README.md'
alias cdgm='cd $HOME/src/github.com/solo-io/gloo-mesh'
alias nvgm='nvim $HOME/src/github.com/solo-io/gloo-mesh/README.md'
alias cdgmui='cd $HOME/src/github.com/solo-io/gloo-mesh-ui'
alias nvgmui='nvim $HOME/src/github.com/solo-io/gloo-mesh-ui/README.md'
alias cdgme='cd $HOME/src/github.com/solo-io/gloo-mesh-enterprise'
alias nvgme='nvim $HOME/src/github.com/solo-io/gloo-mesh-enterprise/README.md'
alias cdea='cd $HOME/src/github.com/solo-io/ext-auth-service'
alias nvea='nvim $HOME/src/github.com/solo-io/ext-auth-service/README.md'
alias cdrl='cd $HOME/src/github.com/solo-io/rate-limiter'
alias nvrl='nvim $HOME/src/github.com/solo-io/rate-limiter/README.md'
alias cdeg='cd $HOME/src/github.com/solo-io/envoy-gloo'
alias nveg='nvim $HOME/src/github.com/solo-io/envoy-gloo/README.md'
alias cdee='cd $HOME/src/github.com/solo-io/envoy-gloo-ee'
alias nvee='nvim $HOME/src/github.com/solo-io/envoy-gloo-ee/README.md'

