# Aliases to reach different repos
alias cdsi='cd $GOPATH/src/github.com/solo-io'
alias cdg='cd $GOPATH/src/github.com/solo-io/gloo'
alias nvg='nvim $GOPATH/src/github.com/solo-io/gloo/README.md'
alias cdgf='cd $GOPATH/src/github.com/solo-io/gloo-fed'
alias nvgf='nvim $GOPATH/src/github.com/solo-io/gloo-fed/README.md'
alias cdsp='cd $GOPATH/src/github.com/solo-io/solo-projects'
alias nvsp='nvim $GOPATH/src/github.com/solo-io/solo-projects/README.md'
alias cdsa='cd $GOPATH/src/github.com/solo-io/solo-apis'
alias nvsa='nvim $GOPATH/src/github.com/solo-io/solo-apis/README.md'
alias cddp='cd $GOPATH/src/github.com/solo-io/dev-portal'
alias nvdp='nvim $GOPATH/src/github.com/solo-io/dev-portal/README.md'
alias cdgm='cd $GOPATH/src/github.com/solo-io/gloo-mesh'
alias nvgm='nvim $GOPATH/src/github.com/solo-io/gloo-mesh/README.md'
alias cdgmui='cd $GOPATH/src/github.com/solo-io/gloo-mesh-ui'
alias nvgmui='nvim $GOPATH/src/github.com/solo-io/gloo-mesh-ui/README.md'
alias cdgme='cd $GOPATH/src/github.com/solo-io/gloo-mesh-enterprise'
alias nvgme='nvim $GOPATH/src/github.com/solo-io/gloo-mesh-enterprise/README.md'
alias cdea='cd $GOPATH/src/github.com/solo-io/ext-auth-service'
alias nvea='nvim $GOPATH/src/github.com/solo-io/ext-auth-service/README.md'
alias cdrl='cd $GOPATH/src/github.com/solo-io/rate-limiter'
alias nvrl='nvim $GOPATH/src/github.com/solo-io/rate-limiter/README.md'

